### ISSUE TITLE
Error submitting data. Reason: HTTP Error 400: Bad Request.

### ISSUE THREAD

**Issue by wh1test** [smetj/nscaweb#12]
I have 3 slave nagios servers which send check results to master server through NSCAWeb. Everything worked fine. Today I added new services (~500) on 2 nagios slaves and one of them faced problem:
NSCAweb: Error submitting data to NSCAweb http://10.10.10.22:5668/queue. Reason: HTTP Error 400: Bad Request. Delivery queue left 0 items. Size: 0 bytes
NSCAweb: Setting submitlock and wait for 1 seconds.
NSCAweb: Error submitting data to NSCAweb http://10.10.10.22:5668/queue. Reason: HTTP Error 400: Bad Request. Delivery queue left 57 items. Size: 9519 bytes
NSCAweb: Setting submitlock and wait for 2 seconds.
... and so on. 
Another servers hasn't problems. Configs are the same on all slaves. I tried to reinstall nscaweb on the slave, but it helped only for a few minutes. How to resolve this issue?? Please help!

**Comment by smetj** [comment]
I was not really able to reproduce this. No more feedback, close issue.  Please reopen when problem occurs again.
