### ISSUE TITLE
Error submitting data to /var/spool/icinga/cmd/icinga.cmd. Reason: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by msciciel** [smetj/nscaweb#14]
We encountered problem described below:

Feb  8 18:33:52 icinga1 NSCAweb: Error submitting data to /var/spool/icinga/cmd/icinga.cmd. Reason: 'ascii' codec can't encode character u'\u017c' in position 7873: ordinal not in range(128). Delivery queue left 0 items. Size: 0 bytes

If that occur then nscaweb stops to submit any check to nagios/icinga backend.

**Comment by smetj** [comment]
Just pulled in your fix, thanks for reporting/fixing!
